name: FISCO-BCOS GitHub Actions
on:
  push:
    branches-ignore:
      - "**-1.3"
      - "**-1.5"
    tags-ignore:
      - v1.*
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    # branches:
    #     - '**'
  release:
    types: [published, created, edited]
env:
  CCACHE_DIR: ${{ github.workspace }}/ccache

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/cache@v1.1.2
        id: cache
        with:
          path: deps/src
          key: deps-v1-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            deps-v1-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            deps-v1-${{ runner.temp }}-${{ github.base_ref }}-
            deps-v1-${{ runner.temp }}-
      - uses: actions/cache@v1.1.2
        id: ccache
        with:
          path: ccache
          key: ccache-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            ccache-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            ccache-${{ runner.temp }}-${{ github.base_ref }}-
            ccache-${{ runner.temp }}-
      - name: install macOS dependencies
        if: runner.os == 'macOS'
        run: brew install openssl@1.1 ccache gmp
      - name: install Ubuntu dependencies
        if: runner.os == 'Linux'
        run: sudo apt install -y git curl build-essential clang cmake libssl-dev zlib1g-dev ccache libgmp-dev flex bison patch
      - name: configure
        run: cmake -DTESTS=ON -DCRYPTO_EXTENSION=ON .
      - name: compile
        run: make -j2
      - name: run uint tests
        run: CTEST_OUTPUT_ON_FAILURE=TRUE make test
  macOS_integration_test:
    name: build_integration_test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/cache@v1.1.2
        id: cache
        with:
          path: deps/src
          key: deps-v1-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            deps-v1-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            deps-v1-notest-${{ runner.temp }}-${{ github.base_ref }}-
            deps-v1-notest-${{ runner.temp }}-
            deps-v1-${{ runner.temp }}-
      - uses: actions/cache@v1.1.2
        id: ccache
        with:
          path: ccache
          key: ccache-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            ccache-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            ccache-notest-${{ runner.temp }}-${{ github.base_ref }}-
            ccache-notest-${{ runner.temp }}-
      - name: install macOS dependencies
        run: brew install openssl@1.1 ccache
      - name: configure
        run: cmake .
      - name: compile
        run: make -j2
      - name: run integration testing
        run: cd tools && bash ci/ci_check.sh
